[package]
name = "pubsub"
version = "0.1.0"
edition = "2024"

[dependencies]
dashmap = "6.1.0"
fasthash = { version = "0.4.0", default-features = false }
futures = "0.3.31"
tokio = { version = "1.47.1", features = ["full"] }
tokio-util = { version = "0.7.16", features = ["codec"] }
